spring.application.name=triageai
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000

server.port=${PORT:8080}