spring.application.name=triageai
spring.datasource.url=jdbc:mysql://un59clooriibwuon:zDVxPMNTDDAWbYDnxKqV@bd85vrdtzlqaxabh2tpv-mysql.services.clever-cloud.com:3306/bd85vrdtzlqaxabh2tpv
spring.datasource.username=un59clooriibwuon
spring.datasource.password=zDVxPMNTDDAWbYDnxKqV

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000